swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "API documentaiton for demo contacts api"
host: "petstore.swagger.io"
basePath: "/api/v1.0/"
schemes:
- "https"
- "http"
paths:
  /api/v1.0/people:
    
    post:
      tags:
      - "People"
      summary: "Create a Person"
      operationId: "post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "List of user object"
        required: true
        schema:
          $ref: "#/definitions/People"
      responses:
        "200":
          description: "people"
      security:
      - Client-key: []

    get:
      tags:
      - "People"
      summary: "Get all people"
      description: ""
      operationId: "get"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - name: "filter"
        in: "query"
        required: false
        type: "string" 
      - name: "sort"
        in: "query"
        required: false
        type: "string" 
      - name: "page"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "pageSize"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "people"
      security:
      - Client-key: []    
      
 
  /api/v1.0/people/{id}/contacts:
    post:
      tags:
      - "Contacts"
      summary: "Create contact for a person"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "List of user object"
        required: true
        schema:
          $ref: "#/definitions/Contacts"
      responses:
        "200":
          description: "people"
      security:
      - Client-key: []


  /api/v1.0/contacts:    
    get:
      tags:
      - "Contacts"
      summary: "Get contacts"
      description: "Get contacts of people"
      operationId: "get"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - name: "q"
        in: "query"
        required: false
        type: "string" 
      - name: "sort"
        in: "query"
        required: false
        type: "string" 
      - name: "page"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      - name: "pageSize"
        in: "query"
        required: false
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "people"
      security:
      - Client-key: [] 

securityDefinitions:
  Client-key:
    type: "apiKey"
    name: "Client-key"
    in: "header"
definitions:
  People:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Tony Stark"
      age:
        type: "integer"
        format: "int32"
        example: 29 
      height:
        type: "string"
        example: "155"  
    xml:
      name: "People"

  Contacts:
    type: "object"
    properties:
      email:
        type: "string"
      number:
        type: "string" 
    xml:
      name: "Contacts" 
      
    